# Generated by Django 5.0.7 on 2024-07-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_cname', models.CharField(max_length=255)),
                ('reg_cemail', models.TextField(max_length=255)),
                ('reg_cphone', models.CharField(max_length=255)),
                ('reg_username', models.CharField(max_length=255)),
                ('reg_psw', models.CharField(max_length=255)),
            ],
        ),
    ]
