# Generated by Django 5.0.7 on 2024-08-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_user', models.CharField(default=None, max_length=250)),
                ('cart_proid', models.IntegerField(null=True)),
                ('cart_name', models.CharField(max_length=250)),
                ('cart_price', models.FloatField(max_length=250)),
                ('cart_image', models.FileField(null=True, upload_to='')),
                ('cart_qty', models.IntegerField()),
                ('cart_amount', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='reg_psw',
            field=models.CharField(max_length=2),
        ),
    ]
