# Generated by Django 5.0.7 on 2024-08-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oder_adress',
            new_name='oder_address',
        ),
    ]
