# Generated by Django 5.1 on 2024-10-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_cats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.category'),
        ),
    ]
