# Generated by Django 5.1 on 2024-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_product_pro_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_price',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
