# Generated by Django 5.1 on 2024-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_category_cat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_price',
            field=models.IntegerField(max_length=250, null=True),
        ),
    ]
